In [ ]:
import numpy as np
matrix=np.random.randint(2,12, size=(2,3))
print('matrix:')
print(matrix)

matrix:
[[10  4  5]
 [ 9  8  9]]


In [ ]:
data_type=matrix.dtype
print('Data type of matrix:', data_type)

Data type of matrix: int64


In [ ]:
mean_value = np.mean(matrix)
print(mean_value)

7.5


In [ ]:
median_value=np.median(matrix)
print(median_value)

8.5


In [ ]:
flat_matrix = matrix.flatten()
unique,counts=np.unique(flat_matrix,return_counts=True)
print(unique, counts)
mode_index =np.argmax(counts)
mode_value =unique[mode_index]
print(mode_value)

[ 4  5  8  9 10] [1 1 1 2 1]
9


In [ ]:
print(mean_value)
print(median_value)
print(mode_value)

7.5
8.5
9


In [ ]:
addition_result = matrix + matrix
print(addition_result)

[[20  8 10]
 [18 16 18]]


In [ ]:
subtraction_result = matrix - matrix
print(subtraction_result)

[[0 0 0]
 [0 0 0]]


In [ ]:
transpose_result = matrix.T
print(transpose_result)

[[10  9]
 [ 4  8]
 [ 5  9]]


In [ ]:
scalar_multiplication_result = matrix*2
print(scalar_multiplication_result)

[[20  8 10]
 [18 16 18]]
